### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by Xrampino** [IBM/elasticsearch-spark-recommender#37]
Thank you for this project, it is very easy to set up and use, yet it is scalable and built on nice software.

I managed to feed it 45M+ ratings and get real-time recommendations on my macbook air. For now I have an issue when people receive recommendations of products with 2 to 5 ratings, so it is pretty weird, but I'll remove them from my sample and see how it goes (or could I tinker with ALS parameters?)

Anyway thank you!

**Comment by stevemart** [comment]
@Xrampino thanks for the kind remarks, all the credit goes to @MLnick :)

**Comment by MLnick** [comment]
Thanks for the feedback and glad to hear this Code Pattern was useful for
you.

For your issue is it that there are some products with only a few ratings?
In those cases it is common to remove them from the training dataset as you
suggest.

You could also try slightly more regularisation (regParam) to see if that
helps.
